***Settings***
Library     SeleniumLibrary

***Variables***
#Dados gerais
${url}          https://demo.testfire.net/index.jsp
${browser}      chrome

#Dados do teste
${user}                     admin
${pass}                     admin
${emailTextFeedBack}        admin@admin.com
${subjectTextFeedBack}      teste
${questionTextFeedBack}     TesteTesteTesteTesteTesteTesteTesteTesteTesteTeste10